title: Jorge | AI Dev & Researcher
description: AI developer and researcher. Explore my projects, publications, and collaborations in artificial intelligence. Open to proposals and new opportunities.
exclude:
  - 'old_web'
  - 'jorgemf.github.io.iml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '.cursorrules'
  - 'ai'
  - 'README.md'
  - 'cv/'
